spring:
  application:
    name: school-service
    description:

  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: school-service-db
      host: localhost
      port: 27017
